### ISSUE TITLE
Installation and running testcode

### ISSUE THREAD

**Issue by GaryWang7** [FertigLab/Homolig#4]
Hi Alex,

I installed Homolig on my end and finished running the testcode-python-clustering-module.sh as well as testcode-r-characterization-module.rmd. It was straightforward to run. I mainly encountered issues with the virtual environment. 

I made these several changes to run testcode-python-clustering-module.sh using wsl-ubuntu:

1. Adjusted the virtual environment path in bin/activate: 
```
# Suppose $PWD is current homolig repo
VIRTUAL_ENV="$PWD/homolig-venv"
export VIRTUAL_ENV
```
2. Used the python in my own Anaconda environment:
```
which python3

/home/gary/miniforge3/bin/python3
```
and installed these packages separately:
```
sudo apt-get update
sudo apt-get -y install gcc
sudo apt-get install g++
mamba install -c conda-forge scanpy python-igraph leidenalg # I am using mamba instead of conda
```
3. Fixed space issue in the command running homolig_format_checker.py, which I had a pull request.
------------------------------------------
I made one change to run the rmd:
1. Change the cores to use from 10 to 1 since I am using a Windows machine and using more than 1 core is not supported:
```
mclapply(input, mc.cores = 10, FUN = temp.fun)
```
It would be great if the users can specify the number of cores to use in the R functions.

Everything else was pretty intuitive, and users like me should be able to run it easily once the git-repo is published.
Thanks!

**Comment by agirgis3** [comment]
Thanks so much Gary - appreciate the feedback. Will incorporate suggestions asap!

**Comment by agirgis3** [comment]
Made updates to the setup process, with specific package versions included to avoid dependency issues. Should be runnable now w/o further modifications!
